async (page) => {
let passed=0;const errors=[];page.on('pageerror',e=>errors.push(e.message));
const base='http://127.0.0.1:4174/settings-exploration/';
const inspect=()=>page.evaluate(()=>window.TabnaxStudy.inspect());
const check=(value,name)=>{if(!value)throw new Error(name);passed++;};
const reset=async()=>{await page.goto(base+'index.html');await page.evaluate(()=>localStorage.removeItem('tabnax.settings-study.v1'));await page.reload();};
const pane=async name=>page.locator('button[data-pane="'+name+'"]').click();
const openDetails=async selector=>{if(!await page.locator(selector).evaluate(e=>e.open))await page.locator(selector+'>summary').click();};
const shot=async name=>page.screenshot({path:'settings-exploration/output/playwright/'+name+'.png',fullPage:true});
await page.setViewportSize({width:1280,height:1000});await reset();
check((await inspect()).engine.map.personal==='M','eight default labels');
await page.locator('#try').click();await page.keyboard.press('l');
check((await page.locator('#selection-result').textContent()).includes('Layout preview'),'direct selection');
check(!(await inspect()).active,'final key closes session immediately');
await page.locator('#try').click();await page.keyboard.press('x');
check((await inspect()).active,'wrong key stays open');check((await page.locator('#selection-result').textContent()).includes('No window has X'),'wrong key explained');
await page.keyboard.press('Escape');check(!(await inspect()).active,'escape cancel');
await openDetails('.test-controls');await page.locator('#dataset').selectOption('10');
check((await inspect()).engine.map.exports==='PJ','ten-window prefix');
await page.locator('#try').click();await page.keyboard.press('p');check((await inspect()).prefix==='P','prefix waits without timer');
await page.keyboard.press('Backspace');check((await inspect()).prefix==='','backspace corrects');
await page.keyboard.type('pj');check((await page.locator('#selection-result').textContent()).includes('Exports'),'consecutive sequence selects');
await page.locator('#try').click();await page.keyboard.press('/');await page.locator('#search').fill('tabnax layout');
check(await page.locator('.target').count()===1,'literal search AND terms');
await page.keyboard.press('Enter');check((await page.locator('#selection-result').textContent()).includes('Layout preview'),'search result selects');
await page.locator('#try').click();await page.keyboard.press('/');await page.locator('#search').fill('no-such-target');check(await page.locator('.target').count()===0,'empty search');
await page.keyboard.press('Escape');check((await inspect()).query===null&&(await inspect()).active,'escape leaves search first');await page.keyboard.press('Escape');
await page.locator('#alphabet').fill('JJKKLL');check(await page.locator('#apply').isDisabled(),'duplicates block apply');check((await page.locator('#alphabet-error').textContent()).includes('repeated'),'duplicate error visible');
check((await inspect()).engine.selection.alphabet==='JKLUIONMHP','invalid alphabet preserves saved state');
await page.locator('#alphabet').fill('JKLU/IONMHP');check((await page.locator('#alphabet-error').textContent()).includes('reserved'),'command alphabet rejected');
await shot('invalid-alphabet');await page.locator('#discard').click();
await page.locator('#hand').selectOption('left');check((await inspect()).draft.map.code==='A','left hand preview');check((await inspect()).engine.map.code==='J','draft does not save labels');
await page.locator('#apply').click();check((await inspect()).cfg.selection.hand==='left','apply saves alphabet');
await page.locator('#undo').click();check((await inspect()).cfg.selection.hand==='right'&&(await inspect()).engine.map.code==='J','undo restores map and config');
await page.locator('#move-right').click();check((await inspect()).draft.selection.alphabet.startsWith('KJ'),'order arrows work');await page.locator('#discard').click();
await page.locator('#remove-ambiguous').click();check(!(await inspect()).draft.selection.alphabet.includes('I'),'I excluded explicitly');check(!(await inspect()).draft.selection.alphabet.includes('O'),'O excluded explicitly');await page.locator('#discard').click();
await page.locator('#policy').selectOption('mnemonic');check((await inspect()).draft.map.notes==='N','mnemonic allocation');await page.locator('#discard').click();
await page.locator('#policy').selectOption('pairs');check(Object.values((await inspect()).draft.map).every(x=>x.length===2),'pair policy preview');
await page.locator('#try').click();await page.keyboard.type('jj');check((await page.locator('#selection-result').textContent()).includes('VS Code'),'draft pair selectable');await page.locator('#discard').click();
await page.locator('#dataset').selectOption('8');await openDetails('#advanced');
await page.locator('#pin-code').fill('K');await page.locator('#pin').click();check((await page.locator('#pin-error').textContent()).includes('belongs'),'occupied pin rejected');
await page.locator('#pin-code').fill('P');await page.locator('#pin').click();check((await page.locator('#pin-error').textContent()).includes('reserved prefix'),'prefix pin rejected');
await page.locator('#pin-code').fill('H');await page.locator('#pin').click();check((await inspect()).draft.map.code==='H','free pin accepted');check((await inspect()).draft.map.lesson==='K','pin does not shift neighbor');
await page.locator('#apply').click();await page.locator('#hand').selectOption('left');check(await page.locator('#apply').isDisabled(),'incompatible pin blocks alphabet');await page.locator('#discard').click();
await page.locator('#reset-labels').click();await page.locator('#dialog-confirm').click();await page.waitForFunction(()=>window.TabnaxStudy.inspect().draft);check(Object.keys((await inspect()).draft.pins).length===0,'reset preview clears pins');await page.locator('#apply').click();
check((await inspect()).engine.map.code==='J','reset compacts labels');
await openDetails('.inventory');await page.locator('[data-rename="lesson"]').click();check((await inspect()).engine.map.lesson==='K','rename stable');
await page.locator('[data-remove="lesson"]').click();check((await inspect()).engine.retired.includes('K'),'closed label retired');
await page.locator('#add-window').click();check((await inspect()).engine.map['new-1']==='H','new target does not reuse retired label');
await page.locator('#layout').selectOption('grid');check(await page.locator('.empty-cell').count()===1,'grid retains hole');await shot('grid-churn');await page.locator('#layout').selectOption('list');
await pane('general');await page.locator('#minimized').uncheck();check(await page.locator('.target').count()===7,'minimized inclusion filters');check((await inspect()).engine.map.personal==='M','excluded retains address');await page.locator('#minimized').check();
await page.locator('#activation').selectOption('hold');check((await page.locator('#activation-help').textContent()).includes('holding'),'hold explanation');
await page.locator('#preview-surface').focus();await page.keyboard.down('ShiftLeft');check((await inspect()).active,'hold surrogate opens');await page.keyboard.up('ShiftLeft');check(!(await inspect()).active,'hold release cancels');
await page.locator('#record').click();await page.keyboard.press('a');check((await page.locator('#shortcut-error').textContent()).includes('Use Control'),'bare shortcut rejected');
await page.keyboard.press('Control+Alt+KeyT');check((await inspect()).cfg.shortcut==='⌃ ⌥ T','shortcut sample recorded');check((await page.locator('#shortcut-error').textContent())==='','valid shortcut clears old error');
await page.locator('#modifier-side').isVisible().then(async visible=>{if(!visible)await page.getByText('Shortcut details',{exact:true}).click();});
await page.locator('#modifier-side').selectOption('left');check((await inspect()).cfg.modifierSide==='left','side preference retained');
await page.locator('#permission-scenario').selectOption('granted');check((await page.locator('#permission-status').textContent()).includes('simulated only'),'permission never claimed real');
await page.locator('#permission-info').click();check((await page.locator('#dialog-copy').textContent()).includes('cannot inspect, request or grant'),'permission detail clear');await page.locator('#dialog-confirm').click();
await shot('general');
await pane('appearance');await page.locator('[name=appearance][value=dark]').check();await page.locator('button[data-theme=sage]').click();
check(await page.locator('body').evaluate(e=>e.classList.contains('dark')&&e.dataset.theme==='sage'),'dark sage applies');
const mapBefore=(await inspect()).engine.map;await page.locator('#label-size').selectOption('extra');await page.locator('#strong-labels').check();
check(await page.locator('.key-label').first().evaluate(e=>getComputedStyle(e).fontSize)==='24px','extra label size');check(JSON.stringify((await inspect()).engine.map)===JSON.stringify(mapBefore),'appearance preserves map');
await page.locator('#simulate-contrast').check();await page.locator('#simulate-motion').check();check(await page.locator('body').evaluate(e=>e.classList.contains('contrast')&&e.classList.contains('no-motion')),'accessibility scenarios');await shot('appearance-dark-sage');
await page.reload();check((await inspect()).cfg.theme==='sage'&&(await inspect()).cfg.labelSize==='extra','preferences persist reload');check(await page.locator('#window-title').textContent()==='Appearance','last pane persists');check((await inspect()).harness.permission==='unknown','permission scenario not persisted');
await page.locator('#restore').click();await page.locator('#dialog-confirm').click();await page.waitForFunction(()=>window.TabnaxStudy.inspect().cfg.theme==='graphite');check((await inspect()).cfg.theme==='graphite'&&(await inspect()).cfg.labelSize==='standard','defaults reset');await page.locator('#undo').click();check((await inspect()).cfg.theme==='sage','reset undo');
await reset();await openDetails('.test-controls');await page.locator('#dataset').selectOption('tabs');check(await page.locator('.target').count()===48,'48 tab fixtures');check(await page.locator('#policy').isDisabled(),'tab namespace fixed pairs');
await page.locator('#try').click();await page.keyboard.type('kl');check((await page.locator('#selection-result').textContent()).includes('Selected Safari'),'tabs pair selection');
await page.locator('#try').click();await page.keyboard.press('k');await shot('tabs-prefix');await page.keyboard.press('Escape');await page.keyboard.press('Escape');
await page.locator('#dataset').selectOption('6');check(await page.locator('.target').count()===6,'six-window fixture');
await pane('appearance');await page.locator('[name=appearance][value=system]').check();await page.locator('#system-appearance').selectOption('dark');check(await page.locator('body').evaluate(e=>e.classList.contains('dark')),'system appearance simulation');
await page.locator('button[data-theme=iris]').click();await shot('appearance-dark-iris');
await reset();
for(const width of [1440,1024,768,620,390,320]){
 await page.setViewportSize({width,height:1000});
 for(const name of ['general','selection','appearance']){await pane(name);check(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),name+' no horizontal overflow '+width);}
}
await shot('compact-320');
await page.setViewportSize({width:860,height:720});await page.evaluate(()=>document.body.style.zoom='2');
check(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),'200 percent zoom reflows');
check(await page.evaluate(()=>{const form=document.querySelector('.settings-column').getBoundingClientRect(),preview=document.querySelector('.preview-column').getBoundingClientRect();return preview.top>=form.bottom-1;}),'zoom stacks form and preview without overlap');await shot('zoom-200');
await page.evaluate(()=>document.body.style.zoom='1');
await page.setViewportSize({width:1280,height:1000});await reset();
await page.locator('#try').click();await page.keyboard.press('Tab');check(!(await inspect()).active,'Tab leaves direct capture');
await page.locator('#alphabet').fill('ASDFGH');check(!(await inspect()).active,'editing input never switches');await page.locator('#discard').click();
await page.locator('#try').click();await page.evaluate(()=>window.dispatchEvent(new Event('blur')));check(!(await inspect()).active,'focus loss cancels');
await page.goto(base+'tabnax-settings.html');check(await page.locator('.target').count()===8,'standalone artifact loads');
check(await page.locator('script[src],link[rel=stylesheet]').count()===0,'standalone embeds code and style');
await page.locator('#try').click();await page.keyboard.press('k');check((await page.locator('#selection-result').textContent()).includes('Keyboard guide'),'standalone selects');
await page.locator('#try').click();await page.keyboard.press('Escape');await shot('selection-final');
check(errors.length===0,'no JavaScript errors: '+errors.join(';'));
return {passed,errors};
}
