#!/usr/bin/env python3
"""Release metadata: bundle build numbers, the Sparkle appcast, and the Homebrew cask."""

import argparse
from email.utils import format_datetime
from datetime import datetime, timezone
import re
import sys
from xml.sax.saxutils import escape, quoteattr

REPOSITORY = "danmartuszewski/tabnax"
BUNDLE_ID = "pl.tabnax.Tabnax"
MINIMUM_MACOS = "15.0"
SEMVER = re.compile(r"^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$")


def parse_version(version):
    match = SEMVER.match(version)
    if not match:
        raise ValueError(f"expected MAJOR.MINOR.PATCH, got {version!r}")
    major, minor, patch = map(int, match.groups())
    if minor > 999 or patch > 999:
        raise ValueError("minor and patch must stay below 1000 to keep build numbers ordered")
    return major, minor, patch


def build_number(version):
    """CFBundleVersion must increase with every release; Sparkle compares it."""
    major, minor, patch = parse_version(version)
    return str(major * 1_000_000 + minor * 1_000 + patch)


def download_url(version, repository=REPOSITORY):
    return f"https://github.com/{repository}/releases/download/v{version}/Tabnax-{version}.dmg"


def appcast(version, length, signature, notes="", published=None, repository=REPOSITORY):
    parse_version(version)
    published = published or datetime.now(timezone.utc)
    release_page = f"https://github.com/{repository}/releases/tag/v{version}"
    description = ""
    if notes.strip():
        # CDATA cannot contain its own terminator; split it across two sections.
        body = notes.strip().replace("]]>", "]]]]><![CDATA[>")
        description = f'\n      <description sparkle:format="markdown"><![CDATA[{body}]]></description>'
    return f"""<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
  <channel>
    <title>Tabnax</title>
    <link>https://github.com/{repository}</link>
    <item>
      <title>Tabnax {escape(version)}</title>
      <pubDate>{format_datetime(published)}</pubDate>
      <sparkle:version>{build_number(version)}</sparkle:version>
      <sparkle:shortVersionString>{escape(version)}</sparkle:shortVersionString>
      <sparkle:minimumSystemVersion>{MINIMUM_MACOS}</sparkle:minimumSystemVersion>
      <sparkle:hardwareRequirements>arm64</sparkle:hardwareRequirements>
      <sparkle:fullReleaseNotesLink>{escape(release_page)}</sparkle:fullReleaseNotesLink>{description}
      <enclosure url={quoteattr(download_url(version, repository))} length="{int(length)}" type="application/x-apple-diskimage" sparkle:edSignature={quoteattr(signature)}/>
    </item>
  </channel>
</rss>
"""


def cask(version, sha256, repository=REPOSITORY):
    parse_version(version)
    if not re.fullmatch(r"[0-9a-f]{64}", sha256):
        raise ValueError("sha256 must be 64 lowercase hex characters")
    url = download_url("#{version}", repository)
    return f'''# Generated by the Tabnax release workflow. Do not edit.
cask "tabnax" do
  version "{version}"
  sha256 "{sha256}"

  url "{url}"
  name "Tabnax"
  desc "Keyboard-driven switcher for windows, browser tabs and apps"
  homepage "https://github.com/{repository}"

  livecheck do
    url :url
    strategy :github_latest
  end

  auto_updates true
  depends_on arch: :arm64
  depends_on macos: ">= :sequoia"

  app "Tabnax.app"

  uninstall quit: "{BUNDLE_ID}"

  zap trash: [
    "~/Library/Application Support/Mozilla/NativeMessagingHosts/pl.tabnax.bridge.json",
    "~/Library/Application Support/zen/NativeMessagingHosts/pl.tabnax.bridge.json",
    "~/Library/Caches/{BUNDLE_ID}",
    "~/Library/Containers/{BUNDLE_ID}.Safari",
    "~/Library/HTTPStorages/{BUNDLE_ID}",
    "~/Library/Preferences/{BUNDLE_ID}.plist",
  ]
end
'''


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    number = commands.add_parser("build-number", help="print CFBundleVersion for a version")
    number.add_argument("version")
    feed = commands.add_parser("appcast", help="write a single-item Sparkle appcast")
    feed.add_argument("--version", required=True)
    feed.add_argument("--length", required=True, type=int)
    feed.add_argument("--signature", required=True)
    feed.add_argument("--notes-file")
    feed.add_argument("--output", required=True)
    formula = commands.add_parser("cask", help="write the Homebrew cask")
    formula.add_argument("--version", required=True)
    formula.add_argument("--sha256", required=True)
    formula.add_argument("--output", required=True)
    for command in (feed, formula):
        command.add_argument("--repository", default=REPOSITORY)
    args = parser.parse_args(argv)
    try:
        if args.command == "build-number":
            print(build_number(args.version))
            return 0
        if args.command == "appcast":
            notes = open(args.notes_file, encoding="utf-8").read() if args.notes_file else ""
            content = appcast(args.version, args.length, args.signature, notes, repository=args.repository)
        else:
            content = cask(args.version, args.sha256, repository=args.repository)
    except ValueError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2
    with open(args.output, "w", encoding="utf-8") as output:
        output.write(content)
    return 0


if __name__ == "__main__":
    sys.exit(main())
